from __future__ import annotations

import re
from pathlib import Path

from .models import CommandResult, PatchInstruction

NAME_ERROR_RE = re.compile(r"NameError:\s+name\s+'([A-Za-z_][A-Za-z0-9_]*)'\s+is\s+not\s+defined")
MODULE_NOT_FOUND_RE = re.compile(
    r"ModuleNotFoundError:\s+No module named '([A-Za-z_][A-Za-z0-9_\.]*)'"
)
IMPORT_NAME_RE = re.compile(
    r"cannot import name '([A-Za-z_][A-Za-z0-9_]*)' from '([A-Za-z_][A-Za-z0-9_\.]*)'"
)
TRACEBACK_FILE_RE = re.compile(r'File "(.+?)", line (\d+)')


class ErrorAutoFixer:
    def __init__(self, repo_path: str):
        self.repo_root = Path(repo_path).resolve()

    def suggest_fix(self, result: CommandResult) -> PatchInstruction | None:
        text = f"{result.stdout}\n{result.stderr}"

        name_error = NAME_ERROR_RE.search(text)
        if name_error:
            missing_name = name_error.group(1)
            traceback_file = self._extract_traceback_file(text)
            if traceback_file is None:
                return None
            target = traceback_file
            if not target.exists():
                return None
            rel_path = self._to_rel_path(target)
            if rel_path is None:
                return None

            file_content = target.read_text(encoding="utf-8")
            missing_is_callable = self._looks_like_callable_usage(
                file_content=file_content,
                name=missing_name,
            )
            if self._is_defined_before_usage(file_content, missing_name, missing_is_callable):
                return None

            if missing_is_callable:
                header = (
                    "# Auto-generated by RepoCoder-Agent MVP.\n"
                    f"def {missing_name}(*args, **kwargs):\n"
                    f'    raise NotImplementedError("Auto-generated stub: {missing_name}")\n\n'
                )
            else:
                header = (
                    "# Auto-generated by RepoCoder-Agent MVP.\n"
                    f"{missing_name} = None\n\n"
                )
            return PatchInstruction(
                file_path=rel_path,
                operation="replace",
                find_text=file_content,
                replace_text=header + file_content,
            )

        import_error = IMPORT_NAME_RE.search(text)
        if import_error:
            symbol, module_name = import_error.groups()
            module_file = self.repo_root.joinpath(*module_name.split(".")).with_suffix(".py")
            if module_file.exists():
                rel_path = self._to_rel_path(module_file)
                if rel_path is None:
                    return None
                content = (
                    "\n\n# Auto-generated by RepoCoder-Agent MVP.\n"
                    f"{symbol} = None\n"
                )
                return PatchInstruction(file_path=rel_path, operation="append", content=content)

        module_not_found = MODULE_NOT_FOUND_RE.search(text)
        if module_not_found:
            module_name = module_not_found.group(1)
            if "." in module_name:
                target = self.repo_root.joinpath(*module_name.split("."))
                file_path = target / "__init__.py"
            else:
                file_path = self.repo_root / f"{module_name}.py"

            rel_path = self._to_rel_path(file_path)
            if rel_path is None:
                return None
            content = (
                "# Auto-generated by RepoCoder-Agent MVP.\n"
                f'"""Placeholder module for {module_name}."""\n'
            )
            return PatchInstruction(file_path=rel_path, operation="create", content=content)

        return None

    def _extract_traceback_file(self, text: str) -> Path | None:
        matches = TRACEBACK_FILE_RE.findall(text)
        if not matches:
            return None
        # Last traceback frame is usually where the exception happened.
        path_str, _line = matches[-1]
        path = Path(path_str)
        if not path.is_absolute():
            path = (self.repo_root / path).resolve()
        return path

    def _to_rel_path(self, abs_path: Path) -> str | None:
        try:
            rel = abs_path.resolve().relative_to(self.repo_root)
            return str(rel).replace("\\", "/")
        except ValueError:
            return None

    def _looks_like_callable_usage(self, file_content: str, name: str) -> bool:
        pattern = re.compile(rf"\b{re.escape(name)}\s*\(")
        return bool(pattern.search(file_content))

    def _is_defined_before_usage(self, file_content: str, name: str, as_callable: bool) -> bool:
        lines = file_content.splitlines()
        usage_line = None
        define_line = None

        if as_callable:
            define_pattern = re.compile(rf"^\s*def\s+{re.escape(name)}\s*\(")
            usage_pattern = re.compile(rf"\b{re.escape(name)}\s*\(")
        else:
            define_pattern = re.compile(rf"^\s*{re.escape(name)}\s*=")
            usage_pattern = re.compile(rf"\b{re.escape(name)}\b")

        for i, line in enumerate(lines, start=1):
            if usage_line is None and usage_pattern.search(line):
                usage_line = i
            if define_line is None and define_pattern.search(line):
                define_line = i
            if usage_line is not None and define_line is not None:
                break

        return define_line is not None and usage_line is not None and define_line < usage_line
